name: fitness_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  animated_splash_screen: ^1.3.0
  fpdart: ^1.1.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gifs/homescreenGIF.gif
    - assets/images/Register_Page_2.png
    - assets/images/register3.1.png
    - assets/images/register3.2.png
    - assets/images/register3.3.png
    - assets/images/successful_registration.png
    - assets/data/food_details.json
    - assets/data/workouts.json
    - assets/images/food_details_cover.jpg
    - assets/images/fullbody1.png
    - assets/images/lowerbody.png
    - assets/images/ab.png
    - assets/images/squats.png
    - assets/images/skipping.png
    - assets/images/warmup.png
    - assets/images/jumping.png
